name: Run Selenium Tests on Push to Dev Team Repo
'on':
  push:
    branches:
      - DevTeamTestSite
  pull_request:
    branches:
      - DevTeamTestSite
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout automation repository
        uses: actions/checkout@v3
        with:
          ref: master
          repository: subodhshukla/DemoSiteTechlistic
          token: '${{ secrets.GITHUB_TOKEN }}'
          path: automation
      - name: Set GitHub Action property
        run: echo "githubAction=true" >> $GITHUB_ENV
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.3'
      - name: Make gradlew executable
        run: |
          cd automation  # Change directory to where gradlew is
          chmod +x gradlew  # Make gradlew executable
      - name: List files in the project directory
        run: >
          echo "Listing files in the repository:"

          cd automation  # Change to the correct directory

          ls -R ./src/test/java  # List all files in the repository to help
          debug
      - name: Install dependencies using Gradle
        run: |
          cd automation  # Change to the correct directory
          ./gradlew build  # Run Gradle build
      - name: Print Source Dirs
        run: |
          cd automation
          ./gradlew printSourceDirs
      - name: Run TestNG Tests
        run: |
          cd automation  # Change to the correct directory
          .\gradlew clean test  # Run the tests
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: automation/build/test-results/test
     # Merging script started
      - name: Wait for 10 seconds to avoid file conflicts
        run: |
         sleep 10
      - name: Checkout devteamtestsite branch
        uses: actions/checkout@v2
        with:
          ref: DevTeamTestSite
      - name: Clean Gradle build directory
        run: |
          cd automation
          ./gradlew clean
          rm -rf automation/build  # Explicitly remove build directory
      - name: Remove workflow files
        run: >
          rm -rf .github/workflows/*  # Remove .yml workflow file from the repository to avoid pushing it

      - name: Wait before Git Merge
        run: |
         echo "Waiting for 20 seconds before merging..."
         sleep 20  # Allow 20 seconds before merging to avoid file conflicts

      - name: Commit and push changes to master
        run: >
          git config --global user.name 'GitHub Actions' 
          git config --global user.email 'actions@github.com' 
          git fetch origin  # Ensure the latest code from remote is fetched 
          git checkout master  # Switch to master branch 
          # Clean working directory 
          git clean -fd  # Remove untracked files and directories 
          # Merge DevTeamTestSite into master 
          git merge origin/DevTeamTestSite --no-ff -m 'Merged build code into master' 
          # Push the merged changes to master 
          git push origin master
