name: Run Selenium Tests on Push to Dev Team Repo

on:
  push:
    branches:
      - DevTeamTestSite  # Trigger the workflow on push to the 'main' branch (can be modified based on your repo)
  pull_request:
    branches:
      - DevTeamTestSite  # Trigger on pull request to the 'main' branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows as the OS for the GitHub runner

    steps:
    - name: Checkout automation repository
      uses: actions/checkout@v3
      with:
        repository: subodhshukla/DemoSiteTechlistic  # Replace with your automation script repo
        token: ${{ secrets.GITHUB_TOKEN }}   # GitHub token to access other repo

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.3'  # You can modify this to the required Gradle version

    - name: Install dependencies using Gradle
      run: gradle clean build

    - name: Run TestNG Tests
      run: ./gradlew test --tests "*"
    #  run: gradle test --tests "TestPackage.TechlisticTestng" --info --stacktrace  # Modify to your test class path
      # or use specific test command if needed (e.g., gradle test)

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/test-results/test  # Path to your test results directory (Gradle default path)
